//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace learn_models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public string employee_id { get; set; }
        public string employee_name { get; set; }
        public string emp_designation { get; set; }
        public string emp_duty_timing { get; set; }
        public string emp_cnic { get; set; }
        public string emp_address { get; set; }
        public string emp_maritalstatus { get; set; }
        public string emp_number { get; set; }
    }
}
