//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace learn_models
{
    using System;
    using System.Collections.Generic;
    
    public partial class foxriverlibrary
    {
        public string book_id { get; set; }
        public string book_name { get; set; }
        public string book_author_name { get; set; }
        public int book_copies { get; set; }
        public string book_shelf_num { get; set; }
    }
}
