//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace learn_models
{
    using System;
    using System.Collections.Generic;
    
    public partial class inventory
    {
        public string item_id { get; set; }
        public string item_name { get; set; }
        public int item_quantity { get; set; }
        public Nullable<System.DateTime> item_expiry { get; set; }
        public string item_type { get; set; }
    }
}
