//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace learn_models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FoxRiverDatabaseEntities3 : DbContext
    {
        public FoxRiverDatabaseEntities3()
            : base("name=FoxRiverDatabaseEntities3")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Crime_Information> Crime_Information { get; set; }
        public virtual DbSet<prisoner_info> prisoner_info { get; set; }
        public virtual DbSet<Prisoner_Medical> Prisoner_Medical { get; set; }
        public virtual DbSet<prisoner_property_cash> prisoner_property_cash { get; set; }
        public virtual DbSet<prisoner_work_allotment> prisoner_work_allotment { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<Employee> Employees { get; set; }
        public virtual DbSet<foxriverlibrary> foxriverlibraries { get; set; }
        public virtual DbSet<inventory> inventories { get; set; }
        public virtual DbSet<VisiterLog> VisiterLogs { get; set; }
    }
}
