//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace learn_models
{
    using System;
    using System.Collections.Generic;
    
    public partial class prisoner_property_cash
    {
        public int p_id { get; set; }
        public string p_items { get; set; }
        public int item_roomnum { get; set; }
        public string item_shelfnum { get; set; }
    
        public virtual prisoner_info prisoner_info { get; set; }
    }
}
