//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace learn_models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Prisoner_Medical
    {
        public int p_id { get; set; }
        public System.DateTime p_med_date { get; set; }
        public string p_disease { get; set; }
        public int medicalward_num { get; set; }
        public int bed_num { get; set; }
        public int numberofdaysspent { get; set; }
    
        public virtual prisoner_info prisoner_info { get; set; }
    }
}
