//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace learn_models
{
    using System;
    using System.Collections.Generic;
    
    public partial class prisoner_info
    {
        public prisoner_info()
        {
            this.Crime_Information = new HashSet<Crime_Information>();
        }
    
        public int p_id { get; set; }
        public string p_name { get; set; }
        public string p_cnic { get; set; }
        public string p_address { get; set; }
        public string p_homenum { get; set; }
        public bool p_maritalstatus { get; set; }
        public string p_block { get; set; }
        public string p_roomnum { get; set; }
        public System.DateTime p_dateofarrival { get; set; }
        public System.DateTime p_dateofrelease { get; set; }
    
        public virtual Prisoner_Medical Prisoner_Medical { get; set; }
        public virtual prisoner_property_cash prisoner_property_cash { get; set; }
        public virtual prisoner_work_allotment prisoner_work_allotment { get; set; }
        public virtual ICollection<Crime_Information> Crime_Information { get; set; }
    }
}
