//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace learn_models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VisiterLog
    {
        public string visiter_id { get; set; }
        public string visiter_name { get; set; }
        public int p_id { get; set; }
        public string visiter_address { get; set; }
        public string visiter_phonenum { get; set; }
        public string visiter_relation { get; set; }
        public Nullable<System.DateTime> v_date { get; set; }
        public string v_time { get; set; }
    }
}
