//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace adonet
{
    using System;
    using System.Collections.Generic;
    
    public partial class prisoner_crime
    {
        public int p_id { get; set; }
        public int crime_id { get; set; }
    }
}
