//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace adonet
{
    using System;
    using System.Collections.Generic;
    
    public partial class prisoner_info_table
    {
        public int p_id { get; set; }
        public string p_name { get; set; }
        public string p_cnic { get; set; }
        public string p_address { get; set; }
        public int p_homenum { get; set; }
        public bool p_maritalstatus { get; set; }
        public System.DateTime p_dateofarrival { get; set; }
        public System.DateTime p_dateofrelease { get; set; }
        public string p_type { get; set; }
    }
}
